# Made to shush the linter about self.info not being seen anywhere.

from __future__ import annotations
from typing import Protocol
from wubi.info import Info


class BackendProtocol(Protocol):
    """
    Structural type that every mixin expects self to satisfy.
    Implemented concretely by Backend — mixins declare this as their base
    so Pylance knows what attributes and helpers are always available.
    """

    info: Info
    cache: dict
    _is_already_configured: bool

    def _decode(self, value) -> str: ...
    def _find_bcdedit(self) -> str: ...
    def _has_aria2c(self) -> bool: ...
    def contains_partition(self, value) -> bool: ...
    def find_any_iso(self): ...
    def check_EFI(self) -> bool: ...
    def check_file(self, file_path, relpath, md5sums, associated_task=None) -> bool: ...
    def check_iso(self, iso_path, associated_task=None) -> bool: ...
    def extract_file_from_iso(self, iso_path, file_path, output_dir=None, overwrite=False): ...
    def get_distros(self) -> list: ...
    def _get_source_id(self) -> str: ...
    def cache_iso_path(self) -> None: ...